ColorRun.langs = {}

ColorRun.langs["fr"] = {
    ["create_game"] = "Créer une partie",
    ["alreadyqueuec"] = "Il y a déjà une queue créée",
    ["maxroundsreached"] = "Les rounds maximum ne peuvent pas aller au dessus de %s.",
    ["maxplayersreached"] = "Les joueurs maximum ne peuvent pas aller au dessus de %s.",
    ["no_queue"] = "Il n'y a pas de partie déjà créée.",
    ["joinedqueue"] = "%s a rejoint la file d'attente",
    ["leftqueue"] = "%s a quitté la file d'attente",
    ["end_game"] = "La partie est finie !",
    ["end_game_forced"] = "La partie n'a plus assez de joueurs. Fin !",
    ["forceduowith"] = "Vous faites désormais équipe avec: %s !",
    ["noduoss"] = "La partie n'a pas assez de joueur pour être jouée en duos",
    ["start_delayed"] = "Le lancement de la partie a été annulé",
    ["startingin"] = "La partie commence dans %ss.",
    ["already_in_queue"] = "Vous êtes déjà dans la file d'attente",
    ["join_queue"] = "Rejoindre la file d'attente",
    ["exit"] = "Quitter",

    ["my_team"] = "Mon équipe",
    ["owner"] = "Chef de l'équipe",
    ["member"] = "Membre de l'équipe",

    ["invite_member"] = "Inviter un joueur",
    ["invited_by"] = "%s vous a invité dans son équipe",
    ["invited_who"] = "Vous avez invité %s dans votre équipe",
    ["already_invited"] = "%s a déjà une invitation en attente",
    ["canceled_by"] = "%s a annulé son invitation",
    ["you_has_kick"] = "Vous avez viré %s de votre équipe",
    ["you_get_kick"] = "Vous avez été viré par %s",
    ["left_team"] = "%s à quitté l'équipe.",
    ["you_left_team"] = "Vous avez quitté l'équipe.",
    ["game_disbanded"] = "La partie a été supprimée.",
    ["member_join"] = "%s a rejoint votre équipe",
    ["member_disconnect"] = "%s a deconnecté et a quitté votre équipe",

    ["create_game"] = "Créer une partie",
    ["gamemodes"] = "Modes de jeux",
    ["players_max"] = "Joueurs maximum",
    ["rounds_number"] = "Nombre de rounds",
    ["enable_bonuses"] = "Activer les rounds bonus (2 points par round)",
    ["duo_mode"] = "Activer le mode duo",
    ["create_game"] = "Créer la partie",

    ["SWEP_1"] = "1. [CLIQUE GAUCHE] Zone: Placer le premier point ainsi que le deuxieme point de la zone. PNJ: placer le PNJ",
    ["SWEP_2"] = "2. [CLIQUE DROIT] Zone: Generer la zone et la sauvegarder. PNJ: Tourner le PNJ",
    ["SWEP_3"] = "3. [RECHARGER] pour reinitialiser la selection",
    ["SWEP_4"] = "4. [RECHARGER] sans points pour changer de mode",
    ["SWEP_5"] = "5. [FLECHE HAUT ET BAS] Ajuster la rotation du PNJ",

    ["admin_tool_create_zone"] = "Maintenant, veuillez créer la zone",
    ["admin_tool_create_npc"] = "Maintenant, veuillez créer le PNJ",
    ["admin_tool_need_create_zone"] = "Vous devez créer la zone de jeu avant",

    ["has_win_round"] = "%s a gagné la manche",
    ["round_end_scoreboard"] = "Prochaine manche dans %i secondes",
    ["game_end_scoreboard"] = "Partie finie",
    ["close_menu"] = "Fermer",
    ["quit_game"] = "Quitter la partie",
}

ColorRun.langs["en"] = {
    ["create_game"] = "Create a game",
    ["alreadyqueuec"] = "There is already an created queue",
    ["maxplayersreached"] = "The max players can't be more than %s.",
    ["maxroundsreached"] = "The max rounds can't be more than %s.",
    ["no_queue"] = "There is no created game yet.",
    ["joinedqueue"] = "%s has joined the queue",
    ["already_in_queue"] = "You are already in queue",
    ["end_game"] = "The game is over !",
    ["end_game_forced"] = "The game doesn’t have enough players left. Game's over !",
    ["join_queue"] = "Join queue",
    ["start_delayed"] = "The game starting countdown is cancelled",
    ["leftqueue"] = "%s has left the queue",
    ["forceduowith"] = "Your now teaming with: %s !",
    ["noduoss"] = "The game hasn't got enough players to be played in duos.",
    ["exit"] = "Exit",

    ["my_team"] = "My Team",
    ["owner"] = "Team's leader",
    ["member"] = "Team's member",

    ["invite_member"] = "Invite a player",
    ["invited_by"] = "%s invited you in her team",
    ["invited_who"] = "You has invited %s in your team",
    ["already_invited"] = "%s has already an pending invitation",
    ["canceled_by"] = "Invitation canceled by %s",
    ["you_has_kick"] = "You has kicked %s from your team",
    ["you_get_kick"] = "You get kicked by %s",
    ["left_team"] = "%s left the team.",
    ["you_left_team"] = "You left the team.",
    ["game_disbanded"] = "The game has been disbanded.",
    ["member_join"] = "%s has joined your team",
    ["member_disconnect"] = "%s has disconnected and leave your team",
    
    ["create_game"] = "Create game",
    ["gamemodes"] = "Gamemodes",
    ["players_max"] = "Players Max",
    ["rounds_number"] = "Rounds number",
    ["enable_bonuses"] = "Enable bonuses rounds (2 points per rounds)",
    ["duo_mode"] = "Enable duo mode",
    ["create_game"] = "Create game",
    ["SWEP_1"] = "1. [LEFT CLICK] Zone: Place first point and second point of the zone. NPC: Place NPC",
    ["SWEP_2"] = "2. [RIGHT CLICK] Zone: Generate the zone and save him in the data. NPC: Rotate NPC",
    ["SWEP_3"] = "3. [RELOAD] Reset vector you have entered with left click",
    ["SWEP_4"] = "4. [RELOAD] Change mode when no vector entered",
    ["SWEP_5"] = "5. [ARROW DOWN & UP] Adjust NPC rotation",

    ["admin_tool_create_zone"] = "Now, create the zone",
    ["admin_tool_create_npc"] = "Now, create the npc",
    ["admin_tool_need_create_zone"] = "Before, you need to setup the game zone",

    ["has_win_round"] = "%s has win this round",
    ["round_end_scoreboard"] = "Next round in %i seconds",
    ["game_end_scoreboard"] = "Game ended",

    ["close_menu"] = "Close",
    ["quit_game"] = "Quit game",
}